### ISSUE TITLE
Package to be used with qt-pods

### ISSUE THREAD

**Issue by jacob3141** [Kernald/redmine-qt#1]
See here for reference:
https://github.com/cybercatalyst/qt-pods

**Comment by Kernald** [comment]
While this looks like a really interesting idea (that I'll follow for other projects), I never had a chance to really develop this library. So I'll leave this issue open, but it will probably stay like this for a very long time...

**Comment by jacob3141** [comment]
Okay :) if you need help with packaging just drop me a mail. Feel free to open issues, too.

**Comment by jacob3141** [comment]
I opened a pull request.
