### ISSUE TITLE
How do I use this library?

### ISSUE THREAD

**Issue by ruby232** [Kernald/redmine-qt#5]

**Comment by Kernald** [comment]
Well, I never had the occasion to actually work on it, so it does absolutely nothing right now. However, @xaionaro seems to be working on a fork. Maybe take a look at it.

**Comment by xaionaro** [comment]
I use it for [1]. However the project is stopped (due to decision of our rector) and not complete.

[1] https://devel.mephi.ru/dyokunev/tasks

P.S.: BTW, I was going to rename the library to «qrest» (according to "RESTful" API) and create a new library "qredmine" from the "tasks" project code.

**Comment by fathomssen** [comment]
Hi

my fork on [[https://github.com/fathomssen/qtredmine]] provides a simple std::function callback interface.

Thanks @Kernald and @xaionaro for the great work!

Best regard
Frederick Thomssen

**Comment by xaionaro** [comment]
@fathomssen, thanks for the notification! :)

**Comment by fathomssen** [comment]
And there is some Doxygen documentation on http://fathomssen.github.io/qtredmine

Best regards
Frederick Thomssen
